
[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/mrcrgl/bytesf"

[[constraint]]
  name = "github.com/mrcrgl/timef"
  version = "0.0.1"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true
